# .github/workflows/main_pipeline.yml
name: CI/CD Pipeline with Main Branch Updates

on:
  pull_request:
    branches:
      - 'dev'
      - 'stage'
      - 'test'
      - 'prod'
    types:
      - closed  # Trigger on PR close event to check if merged

jobs:
  handle_pr_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch all branches
      run: git fetch origin +refs/heads/*:refs/remotes/origin/*

    - name: Merge changes into main
      run: |
        git checkout main
        git merge --no-ff origin/${{ github.event.pull_request.base.ref }} --allow-unrelated-histories

    - name: Push changes to main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin main

    # Optionally, trigger further workflows based on conditions or via API calls
    - name: Trigger subsequent workflow via GitHub API
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH="${GITHUB_REF##*/}"
        REPO_OWNER=${{ github.repository_owner }}
        REPO_NAME=$(basename ${{ github.repository }})

        if [[ "$BRANCH" == "dev" ]]; then
          echo "Triggering Dev workflow"
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/dev.yml/dispatches \
            -d '{"ref": "main"}'

        elif [[ "$BRANCH" == "stage" ]]; then
          echo "Triggering Stage workflow"
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/stage.yml/dispatches \
            -d '{"ref": "main"}'

        elif [[ "$BRANCH" == "test" ]]; then
          echo "Triggering Test workflow"
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/test.yml/dispatches \
            -d '{"ref": "main"}'

        elif [[ "$BRANCH" == "prod" ]]; then
          echo "Triggering Prod workflow"
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/prod.yml/dispatches \
            -d '{"ref": "main"}'
        fi
