name: SSL Cert Checker

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  check_ssl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Prepare Environment
        run: mkdir -p ./scripts

      - name: Generate sitelist
        run: echo "github.com:443" > ./scripts/sitelist

      - name: Debugging Step
        run: |
          echo "Current directory: ${PWD}"
          echo "Listing contents of scripts directory:"
          ls -la ./scripts
          echo "Contents of sitelist:"
          cat ./scripts/sitelist
          
      - name: Install HTML to Image Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          pip install imgkit

      - name: Run SSL Cert Checker
        run: |
          chmod +x ./scripts/ssl_checker.sh
          ./scripts/ssl_checker.sh -f ./scripts/sitelist -o terminal
        shell: bash

      - name: Convert HTML to Image
        run: python3 ./scripts/html2img.py ./scripts/cert_check.html ./scripts/cert_check.png

      - name: View Results
        run: cat ./scripts/cert_check.html


