name: workflow_02

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "This is workflow 02 triggered by workflow dispatch."