name: workflow_01

on:
  schedule:
    # This cron syntax triggers the workflow every minute
    - cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      workflow_02:
        description: 'Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: echo "Triggered Workflow 2: ${{ github.event.inputs.workflow_02 }}"