name: workflow_01

on:
  schedule:
    # Triggers the workflow every minute, though note GitHub might throttle very frequent triggers.
    - cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      workflow_02:
        description: 'Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

jobs:
  trigger_workflow_02:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow_02
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO/actions/workflows/workflow_02.yml/dispatches \
          -d '{"ref":"main"}'